### ISSUE TITLE
Script does not work with spaces in directory names

### ISSUE THREAD

**Issue by 0ge** [frej/fast-export#102]
If either the source or the destination repo has a space in their path, the script fails.

    fast-export/hg-fast-export.sh -r  "path/to/source"
    readlink: illegal option -- f
    usage: readlink [-n] [file ...]
    hg-fast-export.sh: line 73: cd: "path/to/destination": No such file or directory

It is very confusing when its the destination that have spaces in it. Escaping with quotes did not help. (It is however easy to work around by simply renaming the repositories or moving them temporarily).

Tested on macOS 10.12.6 and fast-export 7aa82e8.

**Comment by frej** [comment]
> If either the source or the destination repo has a space in their
> path, the script fails.

I can only get it to fail if the git-repo name has a space in it. A
space in the source directory does not make it fail for me.

Are you running v170624, the error message from readlink should have
been fixed in v170617?

Anyway, there was some quoting missing, the branch add-missing-quote
should fix at least that. Please try it and report back.

**Comment by 0ge** [comment]
You are correct, it is only the destination repo that causes the issue. I got confused in the process.

I am however running v170624 and getting the readlink output above.

The new branch works though! 👍

**Comment by frej** [comment]
> I am however running v170624 and getting the readlink output above.

Sorry, now I see that you had the hash in the first report.  Thanks for verifying the fix. Would you care to help me debug the readlink issue? 

The script tries to check if readlink supports `-f` and if it doesn't it tries to do without, and if that fails, it gives an error message. What happens if you run `readlink -f /absolute/path/to/the/hg-fast-export.sh ; echo $?`

**Comment by 0ge** [comment]
I'm away from the computer for the rest of the weekend, but I will check on monday. Feel free to remind me should I forget!

**Comment by frej** [comment]
> I get
>
> readlink: illegal option -- f
> usage: readlink [-n] [file ...]
> 1

Thanks, I'll try to figure out why it does not behave as I think it
should...

**Comment by frej** [comment]
@0ge, could you give the branch avoid-nuisance-error-message a spin? Turns out `cmd 2>&1> /dev/null` does not redirect `stderr` to `/dev/null` but `cmd > /dev/null 2>&1` does. So the logic in the script works, but the user gets a nuisance error printout.

**Comment by 0ge** [comment]
Works! 👍

**Comment by frej** [comment]
Thanks, I'll close this issue then.
