### ISSUE TITLE
Mercurial 4.6 version should not be in `master`

### ISSUE THREAD

**Issue by Himura2la** [frej/fast-export#127]
@frej

The commit e200cec39fac8a8ebb1c7d7690c00d5cb15f0c30 seems to be pushed to `master` оссasionaly, this version should remain in its `hg-4.6-compat` branch or the `revsymbol` usage should be safe with the fallback to `repo.changectx`. Master does mot work now.

That's why

```sh
$ sudo apt install mercurial
Reading package lists... Done
Building dependency tree
Reading state information... Done
mercurial is already the newest version (3.7.3-1ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 15 not upgraded.
```

**Comment by frej** [comment]
> The commit e200cec39fac8a8ebb1c7d7690c00d5cb15f0c30 seems to be pushed
> to `master` оссasionaly, this version should remain in its
> `hg-4.6-compat` branch or the `revsymbol` usage should be safe with
> the fallback to `repo.changectx`. Master does mot work now.

I'm not sure what you mean, are you saying that the current release
(v180610) does not work with Mercurial 4.6? If your issue is that
v180610 no longer works with Mercurial <= 4.6, that is intentional (as
written in the README and in the release notes). I don't have the free
time to stay compatible to more than the current Mercurial release.

**Comment by Himura2la** [comment]
Oh, I see. That's surprising. Seems like this only commit with several lines makes fast-export compatible with version 3.7 which is still widely spread, I guess. I think I can try to reach backward compatibility at least this time. 
In a PR, of course

**Comment by Himura2la** [comment]
The latest version I can officially install is 4.41 https://launchpad.net/~mercurial-ppa/+archive/ubuntu/releases 
Why do you force users to compile from sources? ((

**Comment by Nessworthy** [comment]
Wasted hours over this trying to figure out why it wasn't running. Running it in a docker container of `ubuntu:xenial`: Install git & python, and install the latest mercurial linked above using `dkpg -i` from the zip @Himura2la provided seems to actually be working.

Honestly wish I'd read this issue closer when I first started. Cheers man!

**Comment by frej** [comment]
> Why do you force users to compile from sources? 

@Himura2la: I try to keep fast-export compatible with the current stable Mercurial and Git. Due to limited free time I can't afford to spend much time on backwards-compatibility. In this case I find it hard to understand your indignation as nothing hinders you from running the previous release. there are no new features except the port to Mercurial 4.6 and that is clearly shown by the release announcement.

**Comment by Nessworthy** [comment]
I think the sucky part about it is that people (like me) who are dumb, tired, and just want things to work prefer an out-of-the-box solution. All the top searched guides out there suggest you can clone the package from master as-is and have it work. The error you get from running without 4.6 isn't clear and it seemed nowhere else knew why apart from this issue thread.

Of course it would have been fixable by just using my eyes.

**Comment by frej** [comment]
> All the top searched guides out there suggest you can clone
> the package from master as-is and have it work. The error you get from
> running without 4.6 isn't clear and it seemed nowhere else knew why
> apart from this issue thread.

The reciprocal argument could be made by a user wanting to run with
master on a distribution which uses Mercurial 4.6. If you want an
out-of-the-box solution you should probably stick to the packages
provided by your distribution.

**Comment by Himura2la** [comment]
https://github.com/frej/fast-export/pull/131 trying to fix this
