### ISSUE TITLE
multiple mercurial branches missing

### ISSUE THREAD

**Issue by nobody93** [frej/fast-export#136]
Hi, 
Could anyone clarify following note / limitation at http://repo.or.cz/fast-export.git:

hg-fast-export supports multiple branches but only named branches with exactly one head each.

In my mercurial repository, it has 10 named  branches, when it exported to git, only master branch is available,  how can I export all mercurial branches?

**Comment by frej** [comment]
If you have non-named branches with multiple heads, fast-export will complain and exit unless you use the `--force` flag. What does `git branch -a` say?

For further help, please have a look at the generic suggestions below:

[This is a canned reply to issues that contain too little information for effective troubleshooting]

Please have a look at this [blog post](https://www.viget.com/articles/tips-for-writing-better-bug-reports) about writing effective bug reports. For fast-export you should at least:

- Report the version of the fast-export you are running, tag and/or hash.

- Check if your problem is solved by using the latest [released hg-fast-export](https://github.com/frej/fast-export/releases).

- Check that your installed versions of Python and Mercurial meet the minimum requirements as specified in the [README](https://github.com/frej/fast-export/blob/master/README.md).

- Explain what you are trying to do, how you are doing it and in what environment.

- If your source repository is publicly available, give the URL.

- If hg-fast-export gives an error message and a backtrace, include that in the issue.

**Comment by nobody93** [comment]
Thanks frej, it was not clear in Notes/Limitations to support multiple branches at http://repo.or.cz/fast-export.git, but I figured out I need to push every branch, right?

It it is correct, I'll close the issue. Sorry for not understanding the node well.

**Comment by frej** [comment]
There are numerous ways to do that, check the man page for `git push`, depending on what you want to do you cold:

- Add a push refspec matching all the branches you want to push, i.e. `git config remote.<name-of-remote>.push '+refs/heads/*:refs/heads/*'`.
- `push --all`
- `push --mirror`

**Comment by frej** [comment]
@nobody93 did the answers solve your problem? If so please close this issue.
