### ISSUE TITLE
Unable to lock refs/heads

### ISSUE THREAD

**Issue by pa-sy** [frej/fast-export#168]
error: cannot lock ref 'refs/heads/v4/Permissioning': 'refs/heads/v4/Permissioning/Pentest' exists; cannot create 'refs/heads/v4/Permissioning'
error: cannot lock ref 'refs/heads/Gold/v4.3.11': 'refs/heads/Gold' exists; cannot create 'refs/heads/Gold/v4.3.11'
error: cannot lock ref 'refs/heads/release/v4.4.13/inc': 'refs/heads/release/v4.4.13' exists; cannot create 'refs/heads/release/v4.4.13/inc'

Included as an issue for reference. I managed to get round this by renaming the conflicting branches so that brnach path clashes did not occur.

**Comment by frej** [comment]
Which version of git are you using? This is the first time I have seen the verbose error message and it's a big improvement as it gives a clue about what's wrong, previously it only said `error: cannot lock ref 'refs/heads...`.

To help others which encounter this error message, issue #165 also describes some potential gotchas which trigger it.

As this isn't a bug in fast-export, but rather a case of impedance mismatch between Mercurial and Git I will close it.

**Comment by pa-sy** [comment]
I am not asking for this to be repoened but thought I might just highlight something. You have better visibility and have probably already seen this but in case you havent. 
I suspect that the issue here was due to order of processing since the paths that get locked are either parents or children of the path that could not be created.  
Thanks by the way for your effort developing this it was really helpful. Spent ages trying to get this sorted. And having ditched the attempt first time I ended up comining back to it using cygwin.

**Comment by frej** [comment]
The underlying issue is that branch names in git behave as file names (as they are just files and sub-directories under `refs/heads/`, and a path cannot name both a file and a directory, i.e. the branches `a` and `a/b` can never exist at the same time in a git repo. Take a look at #169 and tell me if you think it is useful for others in your situation. Feel free to suggest changes and additions.

I was never involved in the original development, I just took over as maintainer in 2011 when I submitted patches and the original maintainer no longer wanted to maintain it, but thanks anyway. Interest in hg-fast-export really seems to have picked up since Bitbucket announced that they were to discontinue Mercurial support.
