### ISSUE TITLE
Error on mercurial repo with both master and default branch

### ISSUE THREAD

**Issue by acrucifix** [frej/fast-export#182]
Hello,

I am using this tool in order to migrate a bunch of repositories from mercurial to git. First of all, thank you very much for it, it helps me a lot in this migration.

Unfortunately, I stumbled upon a particular problem. In most of the repositories, the "default" branch initially generated by mercurial has been closed and replaced by a self-created "master" branch.

I have replicated this setup on the following public repo [https://bitbucket.org/acrucifix/test-hg2git/commits/](https://bitbucket.org/acrucifix/test-hg2git/commits/)

Using fast-export (commit `ffdd27c`) to migrate this repo to git, I have the following error:
```
Loaded 0 branches
Error: repository has at least one unnamed head: hg r8
/usr/local/Cellar/git/2.24.0_2/libexec/git-core/git-fast-import statistics:
---------------------------------------------------------------------
Alloc'd objects:       5000
Total objects:            0 (         0 duplicates                  )
      blobs  :            0 (         0 duplicates          0 deltas of          0 attempts)
      trees  :            0 (         0 duplicates          0 deltas of          0 attempts)
      commits:            0 (         0 duplicates          0 deltas of          0 attempts)
      tags   :            0 (         0 duplicates          0 deltas of          0 attempts)
Total branches:           0 (         0 loads     )
      marks:           1024 (         0 unique    )
      atoms:              0
Memory total:          2360 KiB
       pools:          2048 KiB
     objects:           312 KiB
---------------------------------------------------------------------
pack_report: getpagesize()            =       4096
pack_report: core.packedGitWindowSize = 1073741824
pack_report: core.packedGitLimit      = 35184372088832
pack_report: pack_used_ctr            =          0
pack_report: pack_mmap_calls          =          0
pack_report: pack_open_windows        =          0 /          0
pack_report: pack_mapped              =          0 /          0
---------------------------------------------------------------------
```

I tried reopening the default branch but it doesn't help.

Do you have any idea how we may solve this in order to keep the commits from both the default and master branches ?

Have a nice day,
Best,

**Comment by frej** [comment]
Searching the closed tickets for the phrase "unnamed head" turns up #9 which explains what the problem is and also gives a workaround. If you only want to convert the default branch, #49 gives you the hint to run with `-b default`. #85 mentions using `--force` to ignore unnamed heads (which is probably not what you want). #86 describes how you can use hg strip to remove them on the hg side. #178 is a pull request (unfortunately abandoned) with a patch that could be helpful.

**Comment by murrayju** [comment]
I have a nearly identical problem. In my case, both the default and master branches are open and needed. I see `Error: repository has at least one unnamed head: hg r193`, which `hg heads` tells me is in fact a named branch, `master`:
```
changeset:   193:110854f46a5a
branch:      master
```

I've tried some of the suggested workarounds, but no luck so far. Anything I try seems to lose at least one of the two branches.

I suspect that the problem here is that fast-export implicitly converts the `default` mercurial branch into the `master` git branch, and then when it gets to the `master` mercurial branch it blows up. Is there a switch to override/disable this behavior?

**Comment by murrayju** [comment]
RTFM I suppose...
> 	-M <name> Set the default branch name (defaults to 'master')

Using `-M dev` solved the problem for me.

**Comment by acrucifix** [comment]
It solved it for me too. I looked at the readme but did not check the usage help 🤦‍♂ so yeah RTFM...
