### ISSUE TITLE
fatal: Invalid raw date "<devnull@localhost> 1441263066 +0530" in ident:  <> <devnull@localhost> 1441263066 +0530

### ISSUE THREAD

**Issue by priteshshah17** [frej/fast-export#184]
Hi

I have added authors file as mentioned one of the issue however I am still getting below error,
`fast-import crash report:
    fast-import process: 11292
    parent process     : 1
    at 2019-12-20 23:55:01 +0000

fatal: Invalid raw date "<devnull@localhost> 1441263066 +0530" in ident:  <> <devnull@localhost> 1441263066 +0530`.

hg fast export version: v180610  and latest available version
Existing issue: https://github.com/frej/fast-export/issues/15 however the resolution mentioned to add authors file did not resolve above issue after adding authors file

Below is the authors raw file content
```
<> = devnull <devnull@localhost>
<>=devnull
<> <devnull@localhost>=devnull <devnull@localhost>

```
Stacktrace:
`Traceback (most recent call last):
  File "hg-fast-export.py", line 691, in <module>
    plugins=plugins_dict))
  File "hg-fast-export.py", line 543, in hg2git
    plugins)
  File "hg-fast-export.py", line 347, in export_commit
    export_file_contents(ctx,man,added,hgtags,fn_encoding,plugins)
  File "hg-fast-export.py", line 223, in export_file_contents
    wr(d)
  File "hg-fast-export.py", line 50, in wr
    wr_no_nl(msg)
  File "hg-fast-export.py", line 47, in wr_no_nl
    sys.stdout.write(msg)
IOError: [Errno 32] Broken pipe
`

I am not able to resolve this error anyway, please advise

**Comment by frej** [comment]
[This is a canned reply to issues that contain too little information for effective troubleshooting]

Please have a look at this [blog post](https://www.viget.com/articles/tips-for-writing-better-bug-reports) about writing effective bug reports. For fast-export you should at least:

- Check that your issue is not already covered by an existing issue. If your issue is similar, but not identical to an existing issue, provide a reference.

- Report the version of the fast-export you are running, tag and/or hash.

- Check if your problem is solved by using the latest [released hg-fast-export](https://github.com/frej/fast-export/releases).

- Check that your installed versions of Python and Mercurial meet the minimum requirements as specified in the [README](https://github.com/frej/fast-export/blob/master/README.md).

- Explain what you are trying to do, how you are doing it and in what environment. This includes relevant parts of the used mapping files.

- If your source repository is publicly available, give the URL.

- If hg-fast-export gives an error message and a backtrace, include that in the issue. Also include the relevant parts of the crash report created by `git fast-import`.

**Comment by priteshshah17** [comment]
Update original post with details mentioned above

**Comment by frej** [comment]
For some reason you end up with an empty author, that is probably because the Mercurial author string fails to parse properly parsed and the author email ends up empty. You need to find out what the full Mercurial author string is and provide a mapping for it. The "Most Recent Commands Before Crash" section in the fast-import crash log and the trace printouts from fast-export should help you to figure that out.

Remember that the mapping file applies to the Mercurial author strings, not to whatever fast-export mis-parses. You say "authors raw file", are you using `--mappings-are-raw`? As otherwise the syntax is wrong.

**Comment by priteshshah17** [comment]
Author is empty in one of the changeset in mercurial and hence I am providing author mapping file. Above i have provided log which above "Most Recent Commands Before Crash".

Yes I am using --mappings-are-raw 

Below is the log above "Most Recent Commands Before Crash",
`fast-import crash report:
    fast-import process: 24880
    parent process     : 1
    at 2019-12-22 16:47:41 +0000

fatal: Invalid raw date "<devnull@localhost> 1441263066 +0530" in ident:  <> <devnull@localhost> 1441263066 +0530`

Can you please help if content of author file mentioned below is correct according to logs,
`<> = devnull <devnull@localhost>
<>=devnull
<> <devnull@localhost>=devnull <devnull@localhost>`

Please advise as nothing is working out.

**Comment by frej** [comment]
The old raw format is deprecated just because it cannot express some particular mappings, for example authors containing `=` or the empty string. Avoid it, unless you cannot convert it to the modern format.

Unless there is some strange unicode magic or character set strangeness going on, an author mapping file looking like this:

```
"<>"="Unknown author <devnull@localhost>"
```

should do the trick. Otherwise I'd suggest that you instrument `fixup_user()` in `hg2git.py` to try to figure out what's going on.

**Comment by priteshshah17** [comment]
Thanks a lot, changing the authors mapping file as suggested above helped me to resolve this issue.
