### ISSUE TITLE
Line 359 breaks when branchname uses unicode

### ISSUE THREAD

**Issue by EraYaN** [frej/fast-export#203]
OS: Ubuntu 19.10
Hg: 4.8.2
Python:  3.7.5
fast-export: 160aa3c

The error is:

```
Traceback (most recent call last):
  File "/fast-export/hg-fast-export.py", line 718, in <module>
    plugins=plugins_dict))
  File "/fast-export/hg-fast-export.py", line 570, in hg2git
    plugins)
  File "/fast-export/hg-fast-export.py", line 359, in export_commit
    (branch.decode('utf8'),type,revision+1,max,len(added),len(changed),len(removed)))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xeb' in position 5: ordinal not in range(128) 
```

In this case the branch name is `belgië` and the repo codec is cp1252. If I remove the `.decode('utf-8')` part from the branch variable, it works.
I'm not sure why that one was added, if it's not fully required, I can make a PR to remove it if you want.

**Comment by chrisjbillington** [comment]
Interestingly the decode() of the bytestring is not what's failing, it's the encode() upon printing it to your terminal. This makes it seem like the issue is that your terminal doesnt support unicode. Weird for Ubuntu - what terminal are you using? What's your LANG environment variable?.

I'll see what I can do - since it's just for printing we could use any old error handler or just print the repr of the bytestring by removing the decode() as you've done, but it would be nice if it worked! Or we can just write the raw bytes using stderr.buffer and leave the terminal to deal with it. 

I would have expected an 'ë' to fail decoding UTF8 if it were actually cp1252 - could you perhaps print the repr() of that bytestring to stderr so I can see which encoding it is?

**Comment by chrisjbillington** [comment]
For what it's worth I did test non ascii branch names, so they work in other cases, I think this must be specific to your environment.

Can you run a python script that just says print("belgië")? I'm kinda expecting that to raise the same error on your system.

**Comment by EraYaN** [comment]
Alright so this is a fairly fresh Ubuntu install.

```
$ echo $LANG
en_US.UTF-8
```

and for the direct print:
```
>>> print("belgië")
belgië
```
my terminal is bash 5.0.3 in whatever the default (gnome?) emulator is.

Adding a repr print to the script it appears it's even weirder, no idea what the encoding is.
```
'belgi\xc3\xab'
```

**Comment by chrisjbillington** [comment]
Cool, thanks. What about sys.stderr.write("belgië") from within hg-fast-export.py?

I'll try to reproduce the issue as well, I have an Ubuntu virtualbox.

**Comment by EraYaN** [comment]
So I changed 
```
for python_cmd in python2 python python3; do
```
to 
```
for python_cmd in python3 python python2; do
```
so it runs under python3 by default, then the problem does not occur. So you might as well just drop py2 (considering the end of support is in sight) and consider this "fixed".

This code at line 28
```py
sys.stderr.write(sys.version)
sys.stderr.write('\n')
sys.stderr.write(sys.stderr.encoding) 
sys.stderr.write('\n')
sys.stderr.write("belgië") 
sys.stderr.write('\n')
exit()
```
gives
python3
```
3.7.5 (default, Nov 20 2019, 09:21:52) 
[GCC 9.2.1 20191008]
UTF-8
belgië
```
python2
```
File "/fast-export/hg-fast-export.py", line 32
SyntaxError: Non-ASCII character '\xc3' in file /fast-export/hg-fast-export.py on line 32, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```
So after adding the required encoding near the top as `# -*- coding: utf-8 -*-` and fixing the `sys.stderr.write(sys.stderr.encoding) ` line to `sys.stderr.write("%s" % sys.stderr.encoding) ` for python 2.
python2 + encoding defined + fix
```
2.7.17 (default, Nov  7 2019, 10:07:09) 
[GCC 9.2.1 20191008]
None
belgië
```
There is some weirdness with unicode in python 2.

**Comment by chrisjbillington** [comment]
Excellent. Indeed, it seems like we can't print unicode strings in PY2 unless we set stderr's encoding.

We should probably do

```
if PY2:
    sys.setdefaultencoding('utf-8')
```

at the top of `hg-fast-export.py`.

Does that fix it?

I think hg-fast-export should keep PY2 compat for the moment, since mercurial has only just reached Python 3 compatibility and won't be in distros until their next releases (not even Arch has Python3-based mercurial by default quite yet due to an important bug). So for hg-fast-export to work on existing distros without the user having to make a virtualenv will require PY2 compat.

**Comment by chrisjbillington** [comment]
Huh, actually this just plain works for me (on Arch), putting this at the top of hg-fast-export.py and running `PYTHON=python2 hg-fast-export.sh <blah>`:

```
x = b'belgi\xc3\xab'
import sys
sys.stderr.write(sys.version)
sys.stderr.write('\n')
sys.stderr.write("%s" % sys.stderr.encoding)
sys.stderr.write('\n')
sys.stderr.write(x.decode('utf8'))
sys.stderr.write('\n')

```

```
2.7.17 (default, Oct 22 2019, 09:14:09) 
[GCC 9.2.0]
UTF-8
belgië
```

[Elsewhere](https://stackoverflow.com/questions/492483/setting-the-correct-encoding-when-piping-stdout-in-python) I see that stderr encoding is set based on whether Python's stdout is a tty or not, and since it's being piped within `hg-fast-export.sh`, that's affecting things.

**Comment by chrisjbillington** [comment]
Ah, the error might be happening with the percent formatting - to put the unicode string in the ascii format string, Python is encoding the unicode string ascii first.

Although I'm still unable to reproduce the issue (still must be system-specific), does adding `from __future__ import unicode_literals` to the top of hg-fast-export.py fix the problem? This will make the string literals the same datatype as on Python 3, and then python should be able to do at least the string percent formatting step without having to encode anything.

**Comment by chrisjbillington** [comment]
Hooray, I can reproduce the problem (sort of - I still don't see it in hg-fast-export, not sure why!):

```
$ python2 -c 'import sys; sys.stdout.write(b"belgi\xc3\xab\n".decode("utf8"))'
belgië

$ python2 -c 'import sys; sys.stdout.write(b"belgi\xc3\xab\n".decode("utf8"))' | cat
Traceback (most recent call last):
  File "<string>", line 1, in <module>
UnicodeEncodeError: 'ascii' codec can't encode character u'\xeb' in position 5: ordinal not in range(128)
```

So the problem is that in Python 2:

* %s formatting of a bytestring with a unicode string, i.e `"%s" % u"foo"` results in a unicode string.
* Writing a unicode string to stderr/stdout uses that stream's encoding
* When the output is being piped somewhere (as it is in hg-fast-export), that encoding is None, which implies ASCII.

Solution is just to not write unicode strings to stderr in Python2. The .decode() should be conditional on it being PY3, otherwise the strings should be left as bytestrings.

**Comment by chrisjbillington** [comment]
Could you test PR#203 as a fix?

**Comment by chrisjbillington** [comment]
Could you test PR #204 as a fix?

**Comment by EraYaN** [comment]
Alright I figured it out, when calling the script using `subprocess.run` from another (python3) script, it breaks. The encoding becomes None in python2. the `__future__` import did not solve anything and `setdefaultencoding` does not seem to existing outside of some special global module.

```py
FAST_EXPORT_SH = Path("./fast-export/hg-fast-export.sh")
repo_dir_hg = Path('./path/to/hg-repo')
repo_dir_git = Path('./path/to/git-repo')
author_map = Path("./author.map")
branch_map = Path("./branch.map")
tag_map = Path("./tag.map")
args= ['bash', FAST_EXPORT_SH.resolve(), '-r', repo_dir_hg.resolve(), '-A', author_map.resolve(), '-B', branch_map.resolve(), '-T', tag_map.resolve()]
res = subprocess.run(args, cwd=repo_dir_git)
if res.returncode != 0:
    exit(res.returncode)
```

**Comment by chrisjbillington** [comment]
Excellent!

FWIW `sys.setdefaultencoding('utf-8')` and `from __future__ import unicode_literals` turned out to be unrelated. `sys.setdefaultencoding('utf-8')` is too low-level (and too late to affect the encoding of the already-opened streams), and the strings were already unicode strings so `unicode_literals` wouldn't have had any effect.
