### ISSUE TITLE
Marks and mappings are empty - how do I do incremental exports?

### ISSUE THREAD

**Issue by simon-whitehead** [frej/fast-export#224]
Hi there,

Sorry if this is a silly question - but how do we do incremental exports? It would appear that the `.git/hg2git-*` files are supposed to have something in them but when I export ... they are empty. Our repository is huge and so I am trying to avoid having to export it each time I'm trying to test this whole process. I've even performed a fresh export - then immediately tried to run an export again (with no changes anywhere) and I get this:

```
Warning: .git/hg2git-marks does not contain any data, this will probably make an incremental import fail
Error: Branch [test5] modified outside hg-fast-export:
62e143d26a74a43d2008732781adcc22b365088e (repo) != None (cache)
```

To be clear - I get the above error when I do absolutely nothing between exporting, then trying to do another export immediately after.

I guess my TLDR is: how do I even do incremental exports?

**Comment by passle-chris** [comment]
I'm running into the same thing with the same question. I had assumed that I could run it a second time and it would just update the new things but it seems that maybe there is some meta data missing or I am just completely misunderstanding what an incremental import is supposed to do...

**Comment by frej** [comment]
I don't remember the details, but have a look at #21 as it covers missing `.git/hg2git-*` and see if your problem is a duplicate.

**Comment by simon-whitehead** [comment]
Its not missing - its empty. The files are created but nothing gets put in them.

`.git/hg2git-mapping` has lots of entries in it. `*state` and `*marks` have nothing. Is there a combination of flags I'm supposed to be passing to make it work?

**Comment by frej** [comment]
> Is there a combination of flags I'm supposed to be passing to make it work?

Incremental imports should work out of the box, no flags needed, in fact, even one-off imports are incremental

Is any of the repos publicly available? I suspect that there is an error or warning message printed during conversion that can give a clue on what is happening. Previously when this kind of error (as in #21) there has been same weird interaction between git, the FS and/or branch names.

**Comment by frej** [comment]
No response in more than 90 days, closing.

**Comment by Strawl** [comment]
Hi! I am having the same issue!

I am trying to convert a huge repository, with history from SVN even (converted later on to Mercurial) 
The first time of converting, everything works, it's when trying to do the conversion a second time ( so new commits can be converted), that it fails.

`Warning: .git/hg2git-marks does not contain any data, this will probably make an incremental import fail`
is what I get the first time.

Then later down the line, I get this issue:
```
R28: Exporting simple delta revision 68451/68459 with 0/1/0 added/changed/removed files
master: Exporting simple delta revision 68452/68459 with 0/1/0 added/changed/removed files
Traceback (most recent call last):
  File "D:/hg-git/fast-export/hg-fast-export.py", line 735, in <module>
    plugins=plugins_dict))
  File "D:/hg-git/fast-export/hg-fast-export.py", line 583, in hg2git
    plugins)
  File "D:/hg-git/fast-export/hg-fast-export.py", line 372, in export_commit
    export_file_contents(ctx,man,changed,hgtags,fn_encoding,plugins)
  File "D:/hg-git/fast-export/hg-fast-export.py", line 238, in export_file_contents
    wr(d)
  File "D:/hg-git/fast-export/hg-fast-export.py", line 54, in wr
    wr_no_nl(msg)
  File "D:/hg-git/fast-export/hg-fast-export.py", line 51, in wr_no_nl
    stdout_buffer.write(msg)
IOError: [Errno 22] Invalid argument
```

Which, according to [this issue](https://github.com/frej/fast-export/issues/103), suggests that there is something wrong in the Authors file ( which i didn't even use the first time ) and afterwards it still occurred. 

Mind you this repository has bad branch and tag namings, so to me it is a huge success that it converted at all, so I am considering creating a branch and tag mapping to help streamline the process. 

The repository is not available for the public, but I can support you with other information, if needed. 

Now this most likely has to do something with the repository itself, because with smaller repositories, such issue wasn't presented. Do you perhaps have any other suggestion, than creating a mapping ourselves? 

Also I am using Python 2.7 as well as Mercurial 5.1 (not sure if that's any help)

**Comment by frej** [comment]
> The first time of converting, everything works, it's when trying to do the conversion a second time ( so new commits can be converted), that it fails.

@Strawl , as the git/hg2git-marks ends up empty, I doubt that the initial conversion completed successfully. Check that it returns with a zero exit code and that the git fast-import error log is empty. Reading the full #21 could also give some hints.

**Comment by Strawl** [comment]
@frej 
Thank you, I assumed, that because of the report at the end, that everything went fine. Too
