### ISSUE TITLE
hg-fast-export executed successfully but the files are not copied to the new git repo 

### ISSUE THREAD

**Issue by indranilse** [frej/fast-export#271]
I have successfully run  the hg-fast-import command as below 

command run from the git repo:
 "path where sh file is~\hg-fast-export.sh" -r "repo for the hg"

This is the result
fast-import statistics:
---------------------------------------------------------------------
Alloc'd objects:       5000
Total objects:            0 (         0 duplicates                  )
      blobs  :            0 (         0 duplicates          0 deltas of          0 attempts)
      trees  :            0 (         0 duplicates          0 deltas of          0 attempts)
      commits:            0 (         0 duplicates          0 deltas of          0 attempts)
      tags   :            0 (         0 duplicates          0 deltas of          0 attempts)
Total branches:           0 (         0 loads     )
      marks:           1024 (         0 unique    )
      atoms:              0
Memory total:          2399 KiB
       pools:          2048 KiB
     objects:           351 KiB
---------------------------------------------------------------------
pack_report: getpagesize()            =      65536
pack_report: core.packedGitWindowSize = 1073741824
pack_report: core.packedGitLimit      = 35184372088832
pack_report: pack_used_ctr            =          0
pack_report: pack_mmap_calls          =          0
pack_report: pack_open_windows        =          0 /          0
pack_report: pack_mapped              =          0 /          0
---------------------------------------------------------------------

but after this the new GIT repo is still empty.  Next when I execute the  git checkout HEAD it is throwing error
error: pathspec 'HEAD' did not match any file(s) known to git

Can you please help to resolve.

**Comment by frej** [comment]
Fast-export does not touch your working directory and that is by design. Git `HEAD` is the head of the currently checked out branch, if no branch is checked out, doing `git checkout HEAD` is expected to produce the error you report. As fast-export can't know which of (potentially) multiple converted branches you want checked out after a conversion, it leaves that up to the user. Check the git documentation for how to list and checkout branches.

**Comment by indranilse** [comment]
@frej  sorry to confuse you. What I mean is the GIT repo which we created is still empty after the conversion. it has only the .git folder. If I am still missing any steps can you please guide me with the next steps please if possible.

**Comment by frej** [comment]
Looking at the output again: `Total branches: 0` and `commits: 0`  seems to indicate that nothing was found in the Mercurial repo. The information you have provided is not enough to even guess what could be wrong, there should be output before the information you quoted. In general:

Please have a look at this [blog post](https://www.viget.com/articles/tips-for-writing-better-bug-reports) about writing effective bug reports. For fast-export you should at least:

- Report the version of the fast-export you are running, tag and/or hash.

- Check if your problem is solved by using the latest [released hg-fast-export](https://github.com/frej/fast-export/releases).

- Check that your installed versions of Python and Mercurial meet the minimum requirements as specified in the [README](https://github.com/frej/fast-export/blob/master/README.md).

- Explain what you are trying to do, how you are doing it and in what environment. This includes relevant parts of the used mapping files.

- If your source repository is publicly available, give the URL.

- If hg-fast-export gives an error message and a backtrace, include that in the issue. Also include the relevant parts of the crash report created by `git fast-import`.

**Comment by indranilse** [comment]
@frej Thank you for being patient. Here is the details which I am trying to achieve.

1.

**Comment by frej** [comment]
This is clearly something that is broken or missing in your Windows environment. Your shell fails to execute the Python part of fast-export. It could be that the `PYTHON` environment variable is set to a list of paths when it should point to the python interpreter to use. Issue #160 could be relevant, but I'm just guessing.

Windows is not a platform I have access to, nor interest in, and support for it depends on contributions from users. Checking historic issues marked with the [`wintendo` label](https://github.com/frej/fast-export/issues?q=label%3Awintendo+is%3Aclosed) could give you some pointers.

**Comment by frej** [comment]
@indranilse: Please update this issue if you figure out what is wrong, that way the next Windows user stumbling on this problem is helped too.

**Comment by lorenzznerol** [comment]
This seems to be a bug, perhaps from needed flags or environment variables during runtime or anything else in the .hg or .git folders that needs to be there *before* the start? 

At least, here is a proof by example that I had to run it twice: first run had 0 migration, and the same command run again right after no changes got the migration done.

![2022-03-28_18-18](https://user-images.githubusercontent.com/52793248/160457311-954de7ea-b4f7-45c0-8361-fee9af8a6977.png)
