### ISSUE TITLE
fast-export only converts default branch

### ISSUE THREAD

**Issue by ElonXXIII** [frej/fast-export#308]
I am trying to convert several repositories from Hg to Git, but the fast-export script only converts the default branch. Generally, the documentation does not show how to handle multiple (named) branches. I added bookmarks at the heads of the branches, but it only converted the 5/9 commits of the default branch.

**Comment by frej** [comment]
Branches are supported, with the limitations documented in the ["Notes/Limitations"](https://github.com/frej/fast-export#noteslimitations) section of the README. Your question is not detailed enough to provide more detailed help.

**Comment by frej** [comment]
[This is a canned reply to issues that contain too little information for effective troubleshooting]

Please have a look at this [blog post](https://www.viget.com/articles/tips-for-writing-better-bug-reports) about writing effective bug reports. For fast-export you should at least:

- Check that your issue is not already covered by an existing issue. If your issue is similar, but not identical to an existing issue, provide a reference.

- Report the version of the fast-export you are running, tag and/or hash.

- Check if your problem is solved by using the latest [released hg-fast-export](https://github.com/frej/fast-export/releases).

- Check that your installed versions of Python and Mercurial meet the minimum requirements as specified in the [README](https://github.com/frej/fast-export/blob/master/README.md).

- Explain what you are trying to do, how you are doing it and in what environment. This includes relevant parts of the used mapping files.

- If your source repository is publicly available, give the URL.

- If hg-fast-export gives an error message and a backtrace, include that in the issue. Also include the relevant parts of the crash report created by `git fast-import`.
