### ISSUE TITLE
Fail on old repository

### ISSUE THREAD

**Issue by stoune** [frej/fast-export#32]
I have quite large repository. When I'm exporting to git from hg I'm receiving error:

```
master: Exporting thorough delta revision 2804/4207 with 0/23/1 added/changed/removed files
Traceback (most recent call last):
  File "../fast-export/hg-fast-export.py", line 432, in <module>
    options.statusfile,authors=a,sob=options.sob,force=options.force,hgtags=options.hgtags,notes=options.notes))
  File "../fast-export/hg-fast-export.py", line 362, in hg2git
    c=export_commit(ui,repo,rev,old_marks,max,c,authors,sob,brmap,hgtags,notes)
  File "../fast-export/hg-fast-export.py", line 224, in export_commit
    export_file_contents(ctx,man,changed,hgtags)
  File "../fast-export/hg-fast-export.py", line 136, in export_file_contents
    wr(d)
  File "../fast-export/hg-fast-export.py", line 37, in wr
    wr_no_nl(msg)
  File "../fast-export/hg-fast-export.py", line 34, in wr_no_nl
    sys.stdout.write(msg)
IOError: [Errno 32] Broken pipe
```

I'm used following options:
 ../fast-export/hg-fast-export.sh -r reponame/ --hgtags --hg-hash --force

**Comment by lwcolton** [comment]
@frej This is not a duplicate of #34 .  If you look at the call stack here, sanitize_name is not being called at all.  I am experiencing this issue as well and will provide a pull request if I can.

**Comment by danielpunkass** [comment]
I just ran into this with one of my projects. Same stack trace with export_file_contents, etc. No sanitize_name in the stack.

**Comment by danielpunkass** [comment]
In my case the crash was occuring in fast import because one of my branch names was problematic, even after being sanitized by sanitize_name. The imported repository had a branch named erroneously after a whole ssh:// URL, so something like:

ssh://daniel@where-ever.com/repos/something

The branch name was sanitized to replace the colon, but apparently the "/" also causes problems. I'll submit a pull request with a tweak to add / to the regex for sanitizing. This worked around the issue for me.

**Comment by danielpunkass** [comment]
Anybody else who comes across this issue, the right solution is to use the branch renaming -B flag to alleviate any problems that may be occurring because of the old Mercurial branch names. See explanation on #285.
