### ISSUE TITLE
Archives doesn't contain sharness folder

### ISSUE THREAD

**Issue by pavlonion** [frej/fast-export#326]
I downloaded this release: [v231118.zip](https://github.com/frej/fast-export/archive/refs/tags/v231118.zip)
I tried to use **hg-fast-export.sh** but the script did nothing without any warnings.
I ran **run-tests** and saw that **sharness** directory missed.
After downloading the directory from https://github.com/felipec/sharness.git script have worked and tests were passed.

Please, put **sharness** directory to the release archive and it would be nice to inform script user if it is absent.

**Comment by frej** [comment]
> I tried to use hg-fast-export.sh but the script did nothing without any warnings.

Please see the canned response below, and provide the not already provided information.

> Please, put sharness directory to the release archive and it would be nice to inform script user if it is absent.

This is a [known problem](https://github.com/orgs/community/discussions/31795) with Github releases. As the tests are mainly for developers, and useful development requires working in a git tree, I don't consider that a priority problem. The `run-tests` script should have been removed long ago, now it is (#327). Thank you for stumbling upon it.

[This is a canned reply to issues that contain too little information for effective troubleshooting]

Please have a look at this [blog post](https://www.viget.com/articles/tips-for-writing-better-bug-reports) about writing effective bug reports. For fast-export you should at least:

- Check that your issue is not already covered by an existing issue. If your issue is similar, but not identical to an existing issue, provide a reference.

- Report the version of the fast-export you are running, tag and/or hash.

- Check if your problem is solved by using the latest [released hg-fast-export](https://github.com/frej/fast-export/releases).

- Check that your installed versions of Python and Mercurial meet the minimum requirements as specified in the [README](https://github.com/frej/fast-export/blob/master/README.md).

- Explain what you are trying to do, how you are doing it and in what environment. This includes relevant parts of the used mapping files.

- If your source repository is publicly available, give the URL.

- If hg-fast-export gives an error message and a backtrace, include that in the issue. Also include the relevant parts of the crash report created by `git fast-import`.

**Comment by frej** [comment]
No response in a couple of weeks, closing.
