### ISSUE TITLE
File/Folder names with international characters get mangled

### ISSUE THREAD

**Issue by rojepp** [frej/fast-export#36]
When converting from mercurial to git, file and folder names containing international characters get mangled, and somehow not committed properly. A folder name like `västfolket` will become `v%E4stfolket`, and all files that are affected will show as uncommitted changes in the repo afterwards.

Tested on OSX

**Comment by frej** [comment]
One year since the original report, and no feedback. Closing

**Comment by wburgers** [comment]
Hi,

I am trying to convert a repository from hg to git with fast-export.
There are a few files with an ë in the filename.
I can't get git to detect the full history of those files.

When I try to git log or git blame such a file, git throws an error saying it can't find the file.

I tried to rename the file in the hg repo with an extra commit and do another export.
That makes git blame work after the export which shows which line comes from which commit, but the commits themselves don't show the file changes for those files. git log only shows the last rename commit.
I would like to be able to view the entire log.

I have no clue which encoding hg uses.
Is there any way to retrieve this?

I also tried the export with the -fe windows-1252 encoding, but that didn't change anything.

Any help would be greatly appreciated.

**Comment by frej** [comment]
Hi Willem,

> I am trying to convert a repository from hg to git with fast-export.
> There are a few files with an ë in the filename.  I can't get git to
> detect the full history of those files.
>
> When I try to git log or git blame such a file, git throws an error
> saying it can't find the file.

What happens if you instead of giving the filename to git log, for
example "foo/bar/XëY", give git log "foo/bar/X*", does the file show up
then?

Can you see the file in a graphical tool like gitk?

> I tried to rename the file in the hg repo with an extra commit and do
> another export.  That makes git blame work after the export which
> shows which line comes from which commit, but the commits themselves
> don't show the file changes for those files. git log only shows the
> last rename commit.  I would like to be able to view the entire log.

To me this sounds like the filename you give on the command line is not
in an encoding which matches what's in the converted repo.

> I have no clue which encoding hg uses.  Is there any way to retrieve
> this?

I think hg uses whatever encoding your OS happen to use, and it does not
record it, so you have to guess when converting.

> I also tried the export with the -fe windows-1252 encoding, but that
> didn't change anything.

-fe should be the right thing to do, if you can figure out which
encoding hg is using.

For further help in debugging this, try to create a script which builds
a hg-repo which exhibits the problem, unless you can share the original
repo.

--Frej

**Comment by wburgers** [comment]
Hi,

Thank you for your quick response.

It looks like git log on the command line indeed works by specifying a wildcard.
It shows all commits that changed the file.

gitk also works and shows all modifications in the commit, including those on the files with an ë.

I should add that I tried to verify the repo status after conversion with SourceTree. Right clicking a file and selecting git log or git blame is not working, because it specifies the full filename probably.

But still... After the conversion, git tells me I have untracked files, which are the files with an ë.

In one of the repositories, git wants to rename a file with an ë.
In the other repository, git does not detect the removal of the old file (in different encoding) and only tells me there are new untracked files.
It would be great if it all worked without an extra commit to fix the repo.
It would also be great if git log and git blame would work from Visual Studio's built in git viewer, so I still want to try to fix this completely.

I'll try to create a minimal repository to debug some more and I'll let you know if I can recreate it.
I can't share these two repos unfortunately.

Thank you for your debugging hints so far, I really appreciate it!

**Comment by wburgers** [comment]
With some help from Google and Wikipedia, I was able to find the encoding used on windows.

Windows uses ANSI, but -fe ansi was not working.
> LookupError: unknown encoding: ansi
Another name for the ANSI character set is ISO-8859-1.
So -fe ISO-8859-1 works!

Thanks again for your help!
