### ISSUE TITLE
Conversion crashes due to empty commiter

### ISSUE THREAD

**Issue by marcmast** [frej/fast-export#80]
Hi,

When I'm running a conversion, it fails due to a empty commiter on a (closed) branch.
Is there a way to ignore this/map this on a different user with (for example) an authors file?

**Comment by frej** [comment]
It could be possible, but you don't provide enough information in this report for me to say. Is it fast-export or git fast-import which crashes and with what error message?

If you want more help, please provide a small example which shows your problem (for inspiration, issue #79 is almost an ideal error report).

**Comment by enerxotic** [comment]
Fast-export gives the error. Thanks for referencing to that issue, I'll do my best to provide you with the best possible error report.

First I cloned the fast-export onto test-conversion/fast-export
`mkdir test-conversion
cd test-conversion
git clone https://github.com/frej/fast-export`

Then I exported the path to my environment
`PATH=$PATH:/home/user/test-conversion/fast-export/
export PATH`

Then I cloned the (source) HG project into test-conversion/hg-project
`hg clone -U http://hgurl.com/dir/hg-project
`

Then I cloned the (destination) GIT project
` git clone git-project.git
`
At this point, we have the following directories all in test-conversion:
- fast-export
- hg-project
- git-project

# How to reproduce
Have a commit with an empty user in an closed HG (Mecurial) branch (sadly I can't provide you with a screenshot at the moment)

From directory test-conversion/git-project run the following
`hg-fast-export.sh -r /test-conversion/hg-project --fe iso-8859-1`

It throws the following error:

> fatal: Invalid raw date "<devnull@localhost> 1426071402 +0100" in ident:  <> <devnull@localhost> 1426071402 +0100

When I look at the commit, it says this:

>   commit refs/heads/bugfix-commit
  mark :11956
* committer <> <devnull@localhost> 1426071402 +0100

**Comment by frej** [comment]
This looks like fast-export is feeding git fast-import bad data, the error you see comes from git fast-import. I don't think the problem is an empty committer, but rather that fast-export fails to parse what's there and then presents a bogus committer string to fast-import. When fast-import crashes it produces a crash dump in the top level of the Git repository it was importing into. By looking at the dump you should be able to figure out which commit in the source repo causes the error. When you know that, you can look up the commit on the hg side and map what is in the author field to a proper author name using an author map file.

If that does not the solve the problem, I need either:
- A set of commands which builds a hg repo which triggers the problem you are experiencing.
- Read access to (or a copy of) to the problematic repo.

**Comment by enerxotic** [comment]
Hi Fre,

Thanks for your reply. I have looked up the commit and it sure is empty. See attached. Is it possible to map that to another user?

![upload](https://cloud.githubusercontent.com/assets/18088281/20094556/160af1a4-a5a2-11e6-8134-1575406f11b2.png)

**Comment by frej** [comment]
I see, I would then try the following author map patterns and check if that solves the problem:

'=Something <user@example.com>`
'<>=Something <user@example.com>`
'<> devnull@localhost=Something <user@example.com>`

**Comment by frej** [comment]
Also check if #46 helps.

**Comment by sandromartiniYnap** [comment]
Hi, we have the same problem, but in our repositories has been solved by replacing new line chars from names (in the sanitize function), adding something like this:
`  n=re.sub("[\n\r]+", "", n)`
in 'hg-fast-export.py' just after line 166
but probably there is a better/faster way to do it ... anyway if this is good enough I can do a PR with it.
Thanks, Sandro
