### ISSUE TITLE
hg-fast-export.sh requires bash

### ISSUE THREAD

**Issue by KatolaZ** [frej/fast-export#99]
hg-fast-export.sh seem to have a problem with POSIX sh. In my system /bin/sh is a POSIX shell (dash) and hg-fast-export.sh crashes with the following error:

     ../fast-export/hg-fast-export.sh: 21: ../fast-export/hg-fast-export.sh: Syntax error: Bad fd number

If i run instead:

     bash ../fast-export/hg-fast-export.sh -r ../myrepo/

the export is successful.

**Comment by frej** [comment]
>  ../fast-export/hg-fast-export.sh: 21: ../fast-export/hg-fast-export.sh: Syntax error: Bad fd number

Are you using the latest hg-fast-export? Line 21 is an empty line in the
current release.

**Comment by KatolaZ** [comment]
Yes, I am, and that's why I am puzzled. I got the latest head less than 40 minutes ago...

**Comment by KatolaZ** [comment]
OK, the problem seems to be in the two if blocks added at lines 6-21 in two recent commits (ac887f31 and 02bb982d), since the condition is not inside a test or []. This will not work on POSIX shell. I am sending  a pull request (please check that the tested conditions are correct) .

**Comment by frej** [comment]
I did some digging. The problem is not the condition, as what is checked is the return status of the command, not the output. Your patch in #100 changes the code to check on the output of the command (which should be nothing, at is redirected to /dev/null) instead of the exit status.

Apparently `>& /dev/null` is a bashism, so I had only to replace that with `2>&1 >/dev/null`.

Please try the fix in the [remove-bashism branch](https://github.com/frej/fast-export/tree/remove-bashism) and report back so I can merge it to master if it fixes your problem.

**Comment by KatolaZ** [comment]
yea, you are right, my review was too hasty :) The amended code in remove-bashism works as expected. Thanks!
